#ifndef DT_BINDINGS_ANALOG_STICK_MODES_H_
#define DT_BINDINGS_ANALOG_STICK_MODES_H_

#define ANALOG_STICK_MODE_SWITCH  0
#define ANALOG_STICK_MODE_MOUSE   1
#define ANALOG_STICK_MODE_SCROLL  2

#endif /* DT_BINDINGS_ANALOG_STICK_MODES_H_ */
